django_project/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^example_labeller/', include('example_labeller.urls', namespace='example_labeller',
                                       app_name = 'example_labeller')),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^$', RedirectView.as_view(url='/example_labeller')),
]

example_labeller/urls.py
from django.conf.urls import url

from . import views


app_name = 'example_labeller'
urlpatterns = [
    # Examples:
    # url(r'^$', 'labelling_aas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home, name='home'),
    url(r'^labelling_tool_api$', views.LabellingToolAPI.as_view(), name='labelling_tool_api'),
    url(r'^visualizer$', views.visualizer, name='visualizer'),
]

example_labeller/models.py
from django.db import models
import os
from image_labelling_tool import models as lt_models

# Create your models here.
class ImageWithLabels (models.Model):
    # image
    image = models.ImageField(blank=True)

    # labels
    labels = models.OneToOneField(lt_models.Labels, related_name='image', on_delete=models.CASCADE)

    def __str__(self):
        #
        return str((self.image))[2:]

    def filename(self):
        return os.path.basename(self.image.name)

example_labeller/views.py
import os, datetime

from django.shortcuts import render, get_object_or_404

from django.conf import settings

from image_labelling_tool import labelling_tool
from image_labelling_tool import models as lt_models
from image_labelling_tool import labelling_tool_views
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User

from . import models
import json

import logging


logger = logging.getLogger(__name__)


def home(request):
    #print("request META:", request.META)
    #request_str = "request - 'USERNAME':" + request.META['USERNAME'] + "; REMOTE_ADDR:" +  request.META['REMOTE_ADDR']
    #logger.info(request.META)
    # Force Log out the user if his browser has save the session data and he is being automatically logged in.
    logout(request)
    logged_in = False
    query_string = ''
    assignmentId = 'NOT_SET'
    preview_mode = True

    mturk_urls = ['workersandbox.mturk.com', 'worker.mturk.com']

    try:
        # Check if the request comes from either Sandbox or the production Mturk.
        if any(x in request.META['HTTP_REFERER'] for x in mturk_urls):
            query_string = request.META['QUERY_STRING']
            assignmentId = query_string.split('assignmentId=')[1].split('&')[0]
            log_str = "assignmentId:" + assignmentId
            logger.info(log_str)
            try:
                if 'ASSIGNMENT_ID_NOT_AVAILABLE' not in assignmentId:
                    workerId = query_string.split('workerId=')[1].split('&')[0]
                    log_str = "workerId:" + workerId
                    logger.info(log_str)
                    preview_mode = False
                    if not User.objects.filter(username=workerId).exists():
                        logger.info("New user was created")
                        user = User.objects.create_user(username=workerId, password='Frusciante11')
                        user.save()
                        user = authenticate(username=workerId, password='Frusciante11')
                        login(request, user)
                        logged_in = True
                    else:
                        logger.info("User was logged in")
                        user = authenticate(username=workerId, password='Frusciante11')
                        login(request, user)
                        logged_in = True

            except:
                logger.warning("Something went wrong with user authentication")
    except:
        logger.warning("The request from a non AMT address was made.")

    image_descriptors = [labelling_tool.image_descriptor(
            image_id=img.id, url=img.image.url,
            width=img.image.width, height=img.image.height) for img in models.ImageWithLabels.objects.all()]

    # Convert the label class tuples in `settings` to `labelling_tool.LabelClass` instances
    label_classes = [labelling_tool.LabelClass(*c) for c in settings.LABEL_CLASSES]

    #list example / demonstration images
    image_path = os.path.join(settings.STATIC_ROOT, 'example_images')
    image_dir_files = os.listdir(image_path)

    context = {
        'label_classes': [c.to_json() for c in label_classes],
        'image_descriptors': image_descriptors,
        'initial_image_index': 0,
        'labelling_tool_config': settings.LABELLING_TOOL_CONFIG,
        'example_images': image_dir_files,
        'assignmentId': assignmentId,
        'preview_mode': preview_mode,
        'logged_in': logged_in,
    }
    return render(request, 'index.html', context)


def visualizer(request):
    logged_in = True
    image_descriptors = [labelling_tool.image_descriptor(
            image_id=img.id, url=img.image.url,
            width=img.image.width, height=img.image.height) for img in models.ImageWithLabels.objects.all()]

    # Convert the label class tuples in `settings` to `labelling_tool.LabelClass` instances
    label_classes = [labelling_tool.LabelClass(*c) for c in settings.LABEL_CLASSES]

    # list example / demonstration images
    image_path = os.path.join(settings.STATIC_ROOT, 'example_images')
    image_dir_files = os.listdir(image_path)


    context = {
        'label_classes': [c.to_json()   for c in label_classes],
        'image_descriptors': image_descriptors,
        'initial_image_index': 0,
        'labelling_tool_config': settings.LABELLING_TOOL_CONFIG,
        'example_images': image_dir_files,
        'logged_in': logged_in,

    }
    return render(request, 'visualizer.html', context)



class LabellingToolAPI (labelling_tool_views.LabellingToolViewWithLocking):
    '''Inherits from 'LabellingToolViewWithLocking'. Found in Python sitd-packages'''

    def get_labels(self, request, image_id_str, *args, **kwargs):
        image = get_object_or_404(models.ImageWithLabels, id=image_id_str)
        return image.labels

    def get_next_unlocked_image_id_after(self, request, current_image_id_str, *args, **kwargs):
        unlocked_labels = lt_models.Labels.objects.unlocked()
        unlocked_imgs = models.ImageWithLabels.objects.filter(labels__in=unlocked_labels)
        unlocked_img_ids = [img.id for img in unlocked_imgs]
        print("unlocked_img_ids(child class):", unlocked_img_ids)
        try:
            index = unlocked_img_ids.index(int(current_image_id_str))
            print("Image index: ", index)
        except ValueError:
            print("Image selection ERROR: No unlocked images found")
            return None
        index += 1
        if index < len(unlocked_img_ids):
            print("unlocked image name (returned):",unlocked_img_ids[index])
            return unlocked_img_ids[index]
        else:
            return None


    def get_unlocked_image_ids(self, request, *args, **kwargs):
        '''Overridden method called in the parents get() method'''
        unlocked_labels = lt_models.Labels.objects.unlocked()
        unlocked_imgs = models.ImageWithLabels.objects.filter(labels__in=unlocked_labels)
        unlocked_img_ids = [img.filename() for img in unlocked_imgs]
        unlocked_img_ids = {"unlocked_ids": unlocked_img_ids}
        return unlocked_img_ids

example_labeller/templates/index.html
{% load labelling_tool_tags %}

{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<html>
    <head>
        <title>SMT Labelling Tool</title>

        <script src="/static/jquery/jquery-2.1.1.min.js"></script>

        <link rel="stylesheet" href="/static/jquery/jquery-ui.min.css">
        <script src="/static/jquery/jquery-ui.min.js"></script>

        <script src="/static/d3.min.js"></script>
        <script src="/static/js.cookie.js"></script>
        <script src="/static/json2.js"></script>
        <script src="/static/polyk.js"></script>
        <script src="/static/style/image_slider_script.js"></script>
        <link rel="stylesheet" type="text/css" href="/static/style/image_slider.css" />
        <script>
            // **********************************************************************
            var image_descriptors = {{ image_descriptors | safe }};
            var assignmentId_value = '{{ assignmentId | safe }}';
            var logged_in = '{{ logged_in | safe }}';
        </script>

        {% labelling_tool_scripts %}
    </head>

    <body>

    <h1 style="text-align: center;">SMT Electronics Component Labelling</h1><br>
    <h4 style="text-align: center;">Your task is to mark all the surface mount electronics components in the image below using the <span class="border border-dark">&nbspDraw box </span>&nbsp and <span class="border border-dark">&nbspDraw poly </span>&nbsp tools.</h4><br>

    {% if preview_mode %}
        <h4 style="text-align: center; color:orangered;">WARNING! This task requires a mouse. It cannot be competed on a touchscreen device such as a mobile phone or a tablet.</h4><br>
        <h4 style="text-align: center; color:orangered;">Please watch the video, read the instructions and look at the examples at the bottom to make sure that you understand what to do before pressing Accept.</h4><br>
        <div style="text-align: center;">
            <iframe width="1024" height="576" src="https://www.youtube.com/embed/PB56M6F_5G4" frameborder="0" allowfullscreen ng-show="showvideo"></iframe><br><br>
        </div>
        <h5 style="text-align: center;">This is only a preview page of the task. Use it to play with the options and learn how to use the labelling tool. Try marking at least few components before starting the real work.</h5><br>
        <h5 style="text-align: center;">You are not required to include the pins (legs) of a component if the component has more than 5 of them. See the example images.</h5><br>
        <h4 style="text-align: center;">Press <span class="border border-dark">&nbspF11 </span>&nbsp on your keyboard for full screen.</h4><br><br>
        <h4 style="text-align: center; color:dodgerblue;">Preview Mode.</h4>
        <h5 style="text-align: center; color:dodgerblue;">If you see this text after you have clicked Accept button it means something went wrong on our end and you will not be able to Submit your work. <br> The 'Submit HIT (FINISH)' popup should offer two options 'close' and 'Submit'. Please report this problem if it occurs.</h5>
    {% else %}
        <h4 style="text-align: center;">If you don't know what to mark, please look at the examples at the bottom of the page.<br>(It is better to mark an object if you don't know if it is required. There is no penalty for that.)</h4>
        <h5 style="text-align: center;">You are not required to include the pins (legs) of a component if the component has more than 5 of them. See the example images.</h5><br>
        <h4 style="text-align: center;">Press <span class="border border-dark">&nbspF11 </span>&nbsp on your keyboard for full screen.</h4>
    {% endif %}
    {% if user.is_authenticated %}
            <li>UserID: {{ user.get_username }}</li>
    {% else %}
            <li>User has not been authenticated</li>
    {% endif %}
    <li>Assignment ID: {{ assignmentId | safe }}</li>
    <p>{{ ltapi_url }}</p>
    {% url 'example_labeller:labelling_tool_api' as ltapi_url %}

    {% labelling_tool 1850 1000 label_classes image_descriptors initial_image_index ltapi_url True labelling_tool_config %}

    {% if preview_mode %}
    <!-- Modal Preview Mode -->
    <div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="submitModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">You are in preview mode</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                You are currently in preview mode. If you are sure that you have learned how to use this tool and understand the task, click Accept button on the top right corner to begin.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <!-- Modal Ready to send -->
    <div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="submitModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure you have finished the task?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                Please make sure that all of the components are marked in the same manner as in the example images. <br>Also, as technical errors can happen, please take a screenshot of your work before pressing SUBMIT.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Go Back</button>
                    <button type="button" id="confirmSubmitButton" class="btn btn-primary">YES, SUBMIT WORK (FINISH)</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <br><h2>Instructions for use</h2>

    {% labelling_tool_instructions labelling_tool_config %}

    <h1>Finished Examples:</h1>
    Please try to mark the components in the same way as in these examples.<br><br>
    <div class="slider" id="slider1">
    <!-- Slides -->
        {% for image in example_images %}
            <div style=""><img class="example" src="/static/example_images/{{ image }}"></div>
        {% endfor %}
    <!-- The Arrows -->
    <i class="left" class="arrows" style="z-index:2; position:absolute;"><svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z"></path></svg></i>
    <i class="right" class="arrows" style="z-index:2; position:absolute;"><svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" transform="translate(100, 100) rotate(180) "></path></svg></i>
    <!-- Title Bar -->
{#    <span class="titleBar">#}
{#        <h1>This Slider has all default settings.</h1>#}
{#    </span>#}
    </div><br><br><br>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    </body>
</html>

example_labeller/templates/inline/instructions.html
<p>Zooming and moving the image:</p>
    <ul>
        <li>Use the scroll wheel (or scroll gesture on touch pad) to zoon in and out</li>
        <li><b>Hold Right-click</b> to move the image using your mouse</li>
    </ul>

<p>To label regions of the image:</p>
    <ul>
        {% if drawPolyLabel %}
            <li><strong>Drawing polygonal regions onto the image:</strong>
                <ul>
                    <li>Click the <span class="border border-dark">&nbspDraw poly </span>&nbspbutton</li>
                    <li>Within the image pane, left-click to draw polygonal corners of your region</li>
                    <li>When you have finished the region, right-click to stop</li>
                    <li>You are still in <em>draw poly</em> mode, so you can start left-clicking again to draw the next region</li>
                    <li>To exit <em>draw poly</em> mode, right-click a second time.</li>
                    <li>Fixing mistakes while in drawing mode:
                        <ul>
                            <li>The previous vertex is highlighted with a small pink circle. To delete it, press the
                                '<code>/</code>' key.
                            </li>
                            <li>To insert vertices at a different point in the polygon, press the '<code>,</code>'
                                and '<code>.</code>' keys to cycle through. This also cycles the vertex that is
                                highlighted as the previous vertex (above), allowing you to select vertices to
                                delete.</li>
                        </ul>
                    </li>
                </ul>
            </li>
        {% endif %}

        {% if drawBoxLabel %}
            <li><strong>Drawing rectangular regions onto the image:</strong>
                <ul>
                    <li>Click the <span class="border border-dark">&nbspDraw box </span>&nbspbutton</li>
                    <li>Within the image pane, left-click to place one corner and left click again to place another
                        corner; the tool will create a box between the two</li>
                    <li>Repeat the above for each box that you want to create</li>
                </ul>
            </li>
        {% endif %}

        {% if drawPointLabel %}
            <li><strong>Highlighting points of interest in the image:</strong>
                <ul>
                    <li>Click the <em>Add point</em> button</li>
                    <li>Within the image pane, left-click to place a point marker in the image</li>
                    <li>Repeat the above for each point that you want to create</li>
                </ul>
            </li>
        {% endif %}

        <li><strong>Selecting regions:</strong>
            <ul>
                <li>Selected regions have a red outline, yellow otherwise</li>
                <li>If only <em>one</em> region is selected, clicking the <span class="border border-dark">&nbspDraw poly </span>&nbspbutton will allow you to modify it; you will go back to <em>draw poly</em> mode</li>
                <li>To select a different region, click the <span class="border border-dark">&nbspSelect </span>&nbspbutton and choose a different region by clicking on it. Multiple regions can be selected by holding <em>SHIFT</em> while clicking.</li>
                <li>If multiple regions overlap and you wish to select a region that is obscured, move the
                    pointer over the region that you wish to select; the front-most region will be highlighted.
                    Press the '<code>[</code>' and '<code>]</code>' keys to cycle through the regions under the
                    pointer until the one that you need is highlighted. Left-click to select it.
                </li>
            </ul>
        </li>

        {% if deleteLabel %}
            <li><strong>Deleting regions:</strong>
                <ul>
                    <li>Select regions using the select tool (see above)</li>
                    <li>Click the <span class="border border-dark">&nbspDelete </span>&nbspbutton to delete them; you will be asked for confirmation</li>
                    {% if not deleteConfig.typePermissions.point or not deleteConfig.typePermissions.box or not deleteConfig.typePermissions.polygon or not deleteConfig.typePermissions.composite or not deleteConfig.typePermissions.group %}
                        <li>Please note that you will be unable to delete:
                            <ul>
                                {% if not deleteConfig.typePermissions.point %}<li>point labels</li>{% endif %}
                                {% if not deleteConfig.typePermissions.box %}<li>box labels</li>{% endif %}
                                {% if not deleteConfig.typePermissions.polygon %}<li>polygonal labels</li>{% endif %}
                                {% if not deleteConfig.typePermissions.composite %}<li>composite labels</li>{% endif %}
                                {% if not deleteConfig.typePermissions.group %}<li>group labels</li>{% endif %}
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </li>
        {% endif %}
        <!--
        {% if labelClassSelector %}
            <li><strong>Changing the label of a region:</strong>
                <ul>
                    <li>Select regions using the select tool (see above)</li>
                    <li>Use the drop-down (normally reads <em>UNCLASSIFIED</em>) within the <em>Labels</em> section to change the label</li>
                    <li><strong>Please note:</strong> for regions for which you <em>cannot</em> identify the content, use the <em>Excluded</em> label, this indicates to the system that it should not consider these parts of the image</li>
                </ul>
            </li>
        {% endif %}
        -->

        <li><strong>If the coloured regions are obscuring parts of the image that you need to see:</strong>
            <ul>
                <li>Within the <em>Labels</em> section under <em>Label visibility</em>, choose between <em>hidden</em>
                    <em>faint</em> and <em>full</em> to alter the visibility of the labels.</li>
                <li>Alternatively press the <code>;</code> key to switch between them.</li>
            </ul>
        </li>

        <li><strong>When you are done:</strong>
            <ul>
                <li>When you are satisfied that you have marked out all of the electronics components in the same way as illustrated in examples, click the <b>Submit HIT (FINISH)</b> button within the <em>Current image</em> section.
                    This will send your results to Amazon Mechanical Turk.</li>
            </ul>
        </li>
    </ul>

example_labeller/templates/inline/labelling_tool.html
<div id="{{ tool_id }}"></div>


<script>
    $( document ).ready(function () {
        // The Django based web API uses a class-based view at a single URL for all interaction with
        // the client side tool.
        // Here we define the callbacks that connect the `LabellingTool` instance with the
        // server side API.
        var get_labels = function(image_id) {
            $.ajax({
                type: 'GET',
                url: '{{ labelling_tool_url }}' + '?labels_for_image_id=' + image_id,
                success: function(response) {
                    if (response.error === undefined) {
                        tool.loadLabels(response, null);
                    }
                },
                dataType: 'json'

            });

        };


        {% if enable_locking %}
            var get_next_unlocked_image_id = function(current_image_id) {
                var index;
                $.ajax({
                    type: 'GET',
                    url: '{{ labelling_tool_url }}' + '?next_unlocked_image_id_after=' + current_image_id,
                    success: function(response) {
                        if (response.error === undefined) {
                            tool.goToImageById(response.next_unlocked_image_id);
                            // Added by K. Vigulis ***************************************
                            // replace u' with " and ' with "
                            var ids = response.unlocked_img_ids.replace(/(?!\s|:)((u)(?='))/g, "").replace(/\'/g, '"');
                            ids = JSON.parse(ids);
                            console.log("Unlocked ID List: ", ids);
                            console.log("Next ID: ", response.next_unlocked_image_id);
                            index = image_descriptors.map(function(e) { return e.image_id; }).indexOf(response.next_unlocked_image_id);
                            console.log("Index: ", index);
                            document.getElementById("image_identifier").innerHTML = image_descriptors[index]["img_url"].replace("/media/", '');
                            // ***********************************************************
                        }
                    },
                    dataType: 'json'
                });
                return index;
            };
        {% else %}
            var get_next_unlocked_image_id = null;
        {% endif %}

        var update_labels = function(label_header) {
            if (logged_in) {
                var labels_json_str = JSON.stringify(label_header);

                // Create the POST data
                var post_data = {
                    labels: labels_json_str
                };
                console.log("assignmentId:", assignmentId_value);
                $.ajax({
                    type: 'POST',
                    url: '{{ labelling_tool_url }}',
                    data: post_data,
                    success: function (msg) {
                        tool.notifyLabelUpdateResponse(msg);
                    },
                    dataType: 'json'
                });
                console.log(post_data);
            }
            else {
                console.log("Preview Mode");
            }
        };

        function post(path, params, method) {
            method = method || "post"; // Set method to post by default if not specified.

            // The rest of this code assumes you are not using a library.
            // It can be made less wordy if you use one.
            var form = document.createElement("form");
            form.setAttribute("method", method);
            form.setAttribute("action", path);

            for(var key in params) {
                if(params.hasOwnProperty(key)) {
                    var hiddenField = document.createElement("input");
                    hiddenField.setAttribute("type", "hidden");
                    hiddenField.setAttribute("name", key);
                    hiddenField.setAttribute("value", params[key]);
                    form.appendChild(hiddenField);
                }
            }

            document.body.appendChild(form);
            form.submit();
        }

        // Sends label_header to AMT as a form POST. Called on 'SUBMIT' btn click.
        var send_results_to_AMT = function(label_header) {
            var labels_json_str = JSON.stringify(label_header);
            console.log("Attempting to POST results to AMT...");
            console.log("assignmentId:", assignmentId_value);
            console.log("Results:", labels_json_str);
            // IMPORTANT: remeber to set the correct URL depending on whether you was to test in sandbox or run in production  mode.
            post('https://www.mturk.com/mturk/externalSubmit', {assignmentId:assignmentId_value, results: labels_json_str});
        };


        var tool = new labelling_tool.LabellingTool($("#{{ tool_id }}")[0],
                {{ label_classes | safe }},
                {{ width }},
                {{ height }},
                {{ image_descriptors | safe }},
                get_next_unlocked_image_id(144), // inputs the image index to the 'LabellingTool' constructor.
                get_labels,
                update_labels,
                get_next_unlocked_image_id, // inputs the the whole function to the 'LabellingTool' constructor.
                {{ config | safe }},
                send_results_to_AMT,
        );

        // CSRF Token setup
        var csrftoken = Cookies.get('csrftoken');
{#        var csrftoken = '{{ csrf_token }}';#}
        if (csrftoken != null) {
            // Adapted from Django DOCS
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        }
    });
</script>

example_labeller/templates/visualizer.html
{% load labelling_tool_tags %}

{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<html>
    <head>
        <title>SMT Labelling Tool</title>

        <script src="/static/jquery/jquery-2.1.1.min.js"></script>

        <link rel="stylesheet" href="/static/jquery/jquery-ui.min.css">
        <script src="/static/jquery/jquery-ui.min.js"></script>

        <script src="/static/d3.min.js"></script>
        <script src="/static/js.cookie.js"></script>
        <script src="/static/json2.js"></script>
        <script src="/static/polyk.js"></script>
        <script>
            // **********************************************************************
            var image_descriptors = {{ image_descriptors | safe }};
            var assignmentId_value = '{{ assignmentId | safe }}';
            var logged_in = '{{ logged_in | safe }}';

        </script>

        {% visualizer_scripts %}
    </head>

    <body style="padding-left:1em">



    <h1 style="padding-left:10em">SMT Electronics Component Labelling</h1><br><br>
    {% if user.is_authenticated %}
            <li>UserID: {{ user.get_username }}</li>
    {% else %}
            <li>User has not been authenticated</li>
    {% endif %}

    {% url 'example_labeller:labelling_tool_api' as ltapi_url %}

    {% labelling_tool 1600 1000 label_classes image_descriptors initial_image_index ltapi_url True labelling_tool_config %}



    <br><h2>Instructions for use</h2>

    {% labelling_tool_instructions labelling_tool_config %}


    </body>
</html>